<a href="https://colab.research.google.com/github/flony-hub/2.-Suma-dos-n-meros/blob/main/clase_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Importando la libreria de Numpy**

In [1]:
#-- Importamos la libería
import numpy as np

# **Creando "ndarray" a partir de ceros y unos**

En NumPy, puedes crear arreglos llenos de ceros o unos utilizando las funciones **np.zeros()** y **np.ones()**, respectivamente. Estas funciones son útiles cuando necesitas inicializar matrices o vectores con valores específicos antes de realizar operaciones adicionales.



In [2]:
#-- Generamos el array con una cantidad de 10 ceros y lo mostramos

npVector=np.zeros(10)

In [3]:
#--Geramos el array con una cantidad de 10 unos y lo mostramos
npVectorUnos=np.ones(10)

# **Creando un "ndarray" a partir de cualquier número y en cualquier cantidad**

La función **np.full()** en NumPy se utiliza para crear un arreglo de las dimensiones especificadas, con un valor constante especificado. Esta función es útil cuando necesitas inicializar un arreglo con un valor específico diferente de cero o uno.

In [4]:
#-- Generamos un arreglo de una cantidad x y el valor i y mostramos
matriz=np.full((2,2), 10)
matriz

array([[10, 10],
       [10, 10]])

# **Creando un "ndarray" a partir de un rango**

La función **np.arange()** en NumPy se utiliza para crear arreglos con valores espaciados uniformemente dentro de un intervalo especificado.


In [6]:
#-- Creamos un vector (una dimensión) con diez números consecutivos y mostramos
vectorConsecutivo= np.arange(0, 10, 1)
vectorConsecutivo

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#-- Creamos un vector (una dimensión) con 20 números partiendo desde 1 al 19 y mostramos
vectorVeinte=np.arange(1, 20, 1)
vectorVeinte

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [9]:
#-- Creamos un vector (una dimensión) con números pares partiendo desde 2 hasta 40 y mostramos
vectorPares=np.arange(2, 41, 2)
vectorPares


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

## **Función 'randint'**

La función randint genera números enteros aleatorios dentro de un rango especificado. Puedes definir el rango y la forma del array.

In [11]:
#-- Creamos un array con números aleatorios entre 4 y 500 en una cantidad de 10 y mostramos
arrayAleatorio= np.random.randint(4, 501, 10)
arrayAleatorio

array([369, 474, 246, 464,  20, 300, 107, 464, 211,  65])

## **Accediendo a los valores de un vector**

In [15]:
#-- Generamos un vector (arreglo unidimensional)
vector=np.arange(0, 11, 1)
vector

#-- Acceder a un elemento específico por índice (índice comienza en 0)
vector[2]

#-- Acceder a varios elementos usando segmentación (slice)
vector[1:3]

#-- Modificar un elemento específico
vector[3]=54

# **Tarea 1 - crear ndarray**

1. generar: un array de zeros y otro de unos y otro de números 8 en la cantidad que ud desee.
2. generar un array con números impares partiendo de 3 hasta 93
3. generar un array con números aleatorio en el rango de 8 al 900 en una cantidad de 20

In [ ]:
#-- generar: un array de zeros y otro de unos y otro de números 8 en la cantidad que ud desee.

In [ ]:
#-- generar un array con números impares partiendo de 3 hasta 93

In [ ]:
#-- generar un array con números aleatorio en el rango de 8 al 900 en una cantidad de 20



---


---





# **Ndarray de Dos Dimensiones (Matrices)**

Esta estructura es esencialmente una **matriz** (o un **array bidimensional**)  puede almacenar elementos de cualquier tipo de dato, aunque típicamente se usa para números.

Podemos generar una matriz a partir de un conjunto de listas, por ejemplo

## **Generando una matriz a partir de listas**

In [ ]:
#-- Creamos 3 listas de la misma longitud


In [ ]:
#-- Imprimimos cada una de las listas creadas


In [ ]:
#-- Generando la matriz


In [ ]:
#-- Imprimimos las matriz


## **Generando una matriz a partir de un vector**

In [ ]:
#-- Paso 1) Creamos un ndarray de numpy


In [ ]:
#-- Paso 2) Utilizamos la función reshape() indicando la cantidad de filas y columnas


## **Generando una matriz con números aleatorios**

In [ ]:
#-- Utilizamos la función np.random.randint(2,40,(4,4))

#**Propiedades ndim y shape**

En NumPy, las propiedades **ndim** y **shape**
se utilizan para obtener información sobre las dimensiones y la forma (tamaño) de un arreglo NumPy.

In [ ]:
#-- Tomando como ejemplo a los ndarray que ya hemos creado previamente
#-- vamos a aplicarles las funciones



In [ ]:
#-- Aplicamos ndim - shape
#-- La sintaxis para averiguar la dimension es: ndaray.ndim
#-- La sintaxis para averiguar el tamaño es: ndarray.shape


# **Tarea 2 - crear ndarray de dos dimensiones (matrices)**

1. generar: un array de zeros y otro de unos en la cantidad de 8 elementos
2. generar una matriz a partir de dichos vectores de (2x4) y de (4x2)
3. generar 4 listas de 6 elementos numéricos y construir una matriz de filas y columnas a su gusto.

In [ ]:
#-- generar: un array de zeros y otro de unos en la cantidad de 8 elementos

In [ ]:
#-- generar una matriz a partir de dichos vectores de (2x4) y de (4x2)

In [ ]:
#-- generar 4 listas de 6 elementos numéricos y construir una matriz de filas y columnas a su gusto.

# **Funciones sum(), max(), min(), mean() en Matrices de Numpy**

En NumPy, las funciones **sum()**, **max()**, **min()** y **mean()** son funciones útiles para realizar **operaciones estadísticas** y de **reducción** en matrices y arreglos multidimensionales.

## **Función sum()**

La función **sum()** se utiliza para calcular la suma de los elementos de una matriz a lo largo de un eje específico o de todos los elementos si no se especifica el eje.

In [ ]:
# Crear una matriz a partir de dos listas

In [ ]:
#-- La suma de todos los elementos de la matriz
#-- La sintaxis es np.sum(matriz_a_sumar)


In [ ]:
#-- Otra forma de hacer la misma operación es


## **Función max()**

La función **max()** devuelve el valor máximo a lo largo de un eje especificado o el máximo de todos los elementos si no se especifica el eje.


In [ ]:
# Crear una matriz a partir de tres listas


In [ ]:
#-- Valor máximo de toda la matriz


In [ ]:
#-- Valor máximo a lo largo de las filas (eje 1 o axis = 1)


In [ ]:
#-- Valor máximo a lo largo de las columnas (eje 0 o axis = 0)


## **Funcion min()**

La función **min()** devuelve el valor mínimo a lo largo de un eje especificado o el mínimo de todos los elementos si no se especifica el eje.

***NOTA: La aplicación es similar a la funcion max() solamente que debemos utilizar min()***

## **Función mean()**

La función **mean()** calcula el promedio de los elementos de la matriz a lo largo de un eje especificado o el promedio de todos los elementos si no se especifica el eje.

In [ ]:
# Crear una matriz a partir de dos listas


In [ ]:
#-- El promedio de todos los elementos de la matriz



In [ ]:
#-- El promedio a lo largo de las filas (eje 1 o axis = 1)


In [ ]:
#-- El promedio a lo largo de las columnas (eje 0 o axis = 0)


# **Accediendo a los elementos de una matriz**

Para acceder a los elementos de una **matriz** (arreglo bidimensional) en NumPy, puedes utilizar técnicas de **indexación** y **segmentación**.

In [ ]:
#-- Generamos una matriz (arreglo bidimensional)
#--Imprimimos la matriz


In [ ]:
#-- Acceder a un elemento específico por índices de fila y columna (índices comienzan en 0)


In [ ]:
#-- Acceder a una fila específica


In [ ]:
#-- Acceder a una columna específica


In [ ]:
#-- Modificar un elemento específico
